### ISSUE TITLE
source ~/.bash_profile not saving after close Ubuntu terminal.

### ISSUE THREAD

**Issue by caiodesign** [renatodarrigo/powerful-terminal#2]
Hello,
I'm working in a Ubuntu 16.04 and I need to run `source ~/.bash_profile` every time I close my terminal or restart the OS even running with prefix `sudo`.
Any ideas? Thank you!

**Comment by gnomonunes** [comment]
Hi @caiodesign.
You may have to use `~/.bashrc` instead of `~/.bash_profile`: http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html

To do that run `./install.sh` again and when asked "What is your profile file?", enter `~/.bashrc`.

Also, you shouldn't use `sudo` for any of these as it will change the `root` user files instead.

**Comment by caiodesign** [comment]
It worked!
Thank you so much @gnomonunes!
